#Requires -Version 7
<#
.SYNOPSIS
  Plan-driven multi-terminal supervisor for wmux agent panes.

.DESCRIPTION
  Polls `wmux agent-state`, and when a lane's surface is idle (not blocked),
  injects ONLY the next pending step from a user-authored plan file.
  Never invents steps or opens a supervisor AI session by default.

  Per-lane isolation:
    - each lane has its own surfaceId, label, and step queue
    - log lines always include laneId + surfaceId + stepId

  Records:
    - injected text appears in the target agent terminal (as typed input)
    - append-only JSONL + Markdown log under the plan's log directory
    - plan file is updated in-place (step status / timestamps)

.PARAMETER PlanPath
  Path to the plan JSON (see plan.example.json).

.PARAMETER Once
  Run a single poll cycle and exit.

.PARAMETER DryRun
  Print what would be sent; do not call wmux send / mutate plan status.

.PARAMETER OpenLogSurface
  Open (or refresh) a markdown surface with the log path contents.
  This is a log viewer, not an AI session.

.PARAMETER WmuxCommand
  wmux CLI entry (default: wmux on PATH).
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string] $PlanPath,

  [switch] $Once,
  [switch] $DryRun,
  [switch] $OpenLogSurface,
  [switch] $AllowUnknown,

  [string] $WmuxCommand = 'wmux',
  [string] $LogDir
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Info([string] $Message) {
  Write-Host ("[{0}] {1}" -f (Get-Date -Format 'HH:mm:ss'), $Message)
}

function Get-JsonObject([string] $Path) {
  if (-not (Test-Path -LiteralPath $Path)) {
    throw "Plan not found: $Path"
  }
  $raw = Get-Content -LiteralPath $Path -Raw -Encoding utf8
  return ($raw | ConvertFrom-Json -Depth 100)
}

function Save-JsonObject($Object, [string] $Path) {
  $json = $Object | ConvertTo-Json -Depth 100
  # PowerShell may emit UTF-16 by default; force UTF-8 no BOM for plan files.
  [System.IO.File]::WriteAllText((Resolve-Path -LiteralPath $Path).Path, $json + "`n")
}

function Invoke-WmuxJson {
  param(
    [Parameter(Mandatory = $true)]
    [string[]] $WmuxArgs
  )
  $out = & $WmuxCommand @WmuxArgs 2>&1
  $exit = $LASTEXITCODE
  $text = ($out | ForEach-Object { "$_" }) -join "`n"
  if ($exit -ne 0) {
    throw "wmux $($WmuxArgs -join ' ') failed (exit $exit): $text"
  }
  if ([string]::IsNullOrWhiteSpace($text)) {
    return $null
  }
  try {
    return ($text | ConvertFrom-Json -Depth 50)
  } catch {
    return $text
  }
}

function Get-AgentStateMap {
  $result = Invoke-WmuxJson -WmuxArgs @('agent-state')
  $map = @{}
  if ($null -eq $result) { return $map }

  if ($result.PSObject.Properties.Name -contains 'states' -and $result.states) {
    foreach ($s in @($result.states)) {
      if ($s.surfaceId) { $map[[string]$s.surfaceId] = $s }
    }
  } elseif ($result.PSObject.Properties.Name -contains 'state' -and $result.state) {
    $sid = [string]$result.state.surfaceId
    if ($sid) { $map[$sid] = $result.state }
  }
  return $map
}

function Get-SurfaceState($StateMap, [string] $SurfaceId) {
  if ($StateMap.ContainsKey($SurfaceId)) {
    return $StateMap[$SurfaceId]
  }
  return [pscustomobject]@{
    surfaceId    = $SurfaceId
    state        = 'unknown'
    blockedReason = $null
    runDepth     = 0
  }
}

function Ensure-Dir([string] $Path) {
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Path $Path | Out-Null
  }
}

function New-LogPaths([string] $BaseDir, [string] $PlanName) {
  Ensure-Dir $BaseDir
  $safe = ($PlanName -replace '[^\w\-.]+', '_').Trim('_')
  if ([string]::IsNullOrWhiteSpace($safe)) { $safe = 'plan' }
  return [pscustomobject]@{
    Jsonl = Join-Path $BaseDir "$safe.jsonl"
    Md    = Join-Path $BaseDir "$safe.md"
  }
}

function Write-SupervisorLog {
  param(
    [string] $JsonlPath,
    [string] $MdPath,
    [hashtable] $Event
  )
  $Event['ts'] = (Get-Date).ToUniversalTime().ToString('o')
  $line = ($Event | ConvertTo-Json -Compress -Depth 20)
  Add-Content -LiteralPath $JsonlPath -Value $line -Encoding utf8

  $lane = $Event['laneId']
  $label = $Event['laneLabel']
  $step = $Event['stepId']
  $action = $Event['action']
  $detail = $Event['detail']
  $surf = $Event['surfaceId']
  $mdLine = "- **$($Event['ts'])** | ``$lane`` ($label) | surface ``$surf`` | step ``$step`` | **$action** | $detail"
  if (-not (Test-Path -LiteralPath $MdPath)) {
    @(
      '# Plan supervisor log'
      ''
      'Auto-generated by `Invoke-PlanSupervisor.ps1`. One row per action; lanes are distinguished by `laneId` + `surfaceId`.'
      ''
    ) | Set-Content -LiteralPath $MdPath -Encoding utf8
  }
  Add-Content -LiteralPath $MdPath -Value $mdLine -Encoding utf8
}

function Build-InjectedPrompt {
  param(
    $Plan,
    $Lane,
    $Step,
    [int] $StepIndex,
    [int] $StepCount
  )
  $usePrefix = $true
  if ($null -ne $Plan.promptPrefix) { $usePrefix = [bool]$Plan.promptPrefix }

  if (-not $usePrefix) {
    return [string]$Step.prompt
  }

  $title = if ($Step.title) { [string]$Step.title } else { [string]$Step.id }
  $lines = @(
    "[wmux-supervisor | lane=$($Lane.id) | label=$($Lane.label) | step=$($Step.id) | $StepIndex/$StepCount]"
    "You MUST execute ONLY this planned step. Do not invent follow-up work. Do not change other lanes' scopes."
    "When THIS step is done (or blocked), stop and wait. Do not start the next step yourself."
    "Step title: $title"
    '---'
    [string]$Step.prompt
    '---'
  )
  return ($lines -join "`n")
}

function Send-StepToSurface {
  param(
    [string] $SurfaceId,
    [string] $Text,
    [bool] $SubmitEnter
  )
  # Send as a single write so multi-line plans stay one paste block.
  Invoke-WmuxJson -WmuxArgs @('send', '--surface', $SurfaceId, $Text) | Out-Null
  if ($SubmitEnter) {
    Start-Sleep -Milliseconds 120
    Invoke-WmuxJson -WmuxArgs @('send-key', 'enter', '--surface', $SurfaceId) | Out-Null
  }
}

function Get-NextStep($Lane) {
  $i = 0
  foreach ($step in @($Lane.steps)) {
    $status = [string]$step.status
    if ($status -eq 'pending' -or $status -eq 'in_progress') {
      return [pscustomobject]@{ Index = $i; Step = $step }
    }
    $i++
  }
  return $null
}

function Test-MayDispatch {
  param(
    $SurfaceState,
    [bool] $AllowUnknownState
  )
  $st = [string]$SurfaceState.state
  if ($st -eq 'blocked') { return $false }
  if ($st -eq 'working') { return $false }
  if ($st -eq 'idle') { return $true }
  if ($st -eq 'unknown' -and $AllowUnknownState) { return $true }
  return $false
}

# ── load plan ───────────────────────────────────────────────────────────────
$PlanPath = (Resolve-Path -LiteralPath $PlanPath).Path
$plan = Get-JsonObject $PlanPath
if (-not $plan.lanes) { throw 'Plan has no lanes[]' }
if (-not $plan.name) { $plan | Add-Member -NotePropertyName name -NotePropertyValue 'plan' -Force }

$pollSeconds = 12
if ($plan.pollSeconds) { $pollSeconds = [int]$plan.pollSeconds }
$idleStableSeconds = 8
if ($plan.idleStableSeconds) { $idleStableSeconds = [int]$plan.idleStableSeconds }
$submitEnter = $true
if ($null -ne $plan.submitEnter) { $submitEnter = [bool]$plan.submitEnter }

if (-not $LogDir) {
  $LogDir = Join-Path (Split-Path -Parent $PlanPath) 'logs'
}
$logPaths = New-LogPaths -BaseDir $LogDir -PlanName ([string]$plan.name)

# Per-lane runtime memory (not persisted): lastObservedState, inProgressSince, sawWorking
$runtime = @{}

Write-Info "Plan: $($plan.name)"
Write-Info "File: $PlanPath"
Write-Info "Log:  $($logPaths.Md)"
Write-Info "Mode: $(if ($DryRun) { 'DRY-RUN' } else { 'LIVE' }) | supervisor AI session: OFF (scheduler only)"
Write-Info "Lanes: $(@($plan.lanes).Count) | poll ${pollSeconds}s | idleStable ${idleStableSeconds}s"

if ($OpenLogSurface -and -not $DryRun) {
  try {
    if (-not (Test-Path -LiteralPath $logPaths.Md)) {
      @(
        '# Plan supervisor log'
        ''
        '_waiting for first event…_'
        ''
      ) | Set-Content -LiteralPath $logPaths.Md -Encoding utf8
    }
    Invoke-WmuxJson -WmuxArgs @('markdown', $logPaths.Md) | Out-Null
    Write-Info 'Opened markdown log surface (not an AI session).'
  } catch {
    Write-Warning "OpenLogSurface failed: $_"
  }
}

Write-SupervisorLog -JsonlPath $logPaths.Jsonl -MdPath $logPaths.Md -Event @{
  action    = 'start'
  laneId    = '-'
  laneLabel = '-'
  surfaceId = '-'
  stepId    = '-'
  detail    = "supervisor started plan=$($plan.name) dryRun=$DryRun once=$Once"
}

$cycle = 0
while ($true) {
  $cycle++
  $dirty = $false
  $stateMap = @{}
  try {
    $stateMap = Get-AgentStateMap
  } catch {
    Write-Warning "agent-state failed: $_"
    if ($Once) { break }
    Start-Sleep -Seconds $pollSeconds
    continue
  }

  foreach ($lane in @($plan.lanes)) {
    $laneId = [string]$lane.id
    if (-not $laneId) { continue }
    if ($null -ne $lane.enabled -and -not [bool]$lane.enabled) { continue }

    $surfaceId = [string]$lane.surfaceId
    if ([string]::IsNullOrWhiteSpace($surfaceId) -or $surfaceId -like '*REPLACE*') {
      Write-Warning "Lane ${laneId}: surfaceId not set — skip"
      continue
    }

    if (-not $runtime.ContainsKey($laneId)) {
      $runtime[$laneId] = [pscustomobject]@{
        lastState       = 'unknown'
        inProgressSince = $null
        sawWorking      = $false
        lastDispatchAt  = $null
      }
    }
    $rt = $runtime[$laneId]
    $surf = Get-SurfaceState $stateMap $surfaceId
    $st = [string]$surf.state
    $label = if ($lane.label) { [string]$lane.label } else { $laneId }

    $next = Get-NextStep $lane
    if (-not $next) {
      if ($rt.lastState -ne 'done') {
        Write-Info "Lane $laneId ($label): all steps done"
        Write-SupervisorLog -JsonlPath $logPaths.Jsonl -MdPath $logPaths.Md -Event @{
          action    = 'lane_complete'
          laneId    = $laneId
          laneLabel = $label
          surfaceId = $surfaceId
          stepId    = '-'
          detail    = 'no pending/in_progress steps'
        }
        $rt.lastState = 'done'
      }
      continue
    }

    $step = $next.Step
    $stepId = [string]$step.id
    $status = [string]$step.status
    $stepCount = @($lane.steps).Count
    $stepHuman = $next.Index + 1

    # Track transitions while a step is in flight.
    if ($status -eq 'in_progress') {
      if ($st -eq 'working') { $rt.sawWorking = $true }
      if ($st -eq 'blocked') {
        $reason = if ($surf.blockedReason) { [string]$surf.blockedReason } else { 'awaiting human' }
        Write-Info "Lane $laneId ($label): BLOCKED on step $stepId — $reason (no auto-continue)"
        Write-SupervisorLog -JsonlPath $logPaths.Jsonl -MdPath $logPaths.Md -Event @{
          action    = 'blocked'
          laneId    = $laneId
          laneLabel = $label
          surfaceId = $surfaceId
          stepId    = $stepId
          detail    = $reason
        }
        $rt.lastState = $st
        continue
      }

      $elapsed = 0
      $stableEnough = $false
      if ($rt.inProgressSince) {
        $elapsed = ([datetime]::UtcNow - [datetime]$rt.inProgressSince).TotalSeconds
        $stableEnough = $elapsed -ge $idleStableSeconds
      }

      # Complete step only after idle, and either we saw working or waited long enough
      # (covers agents that finish without a clean working→idle report).
      if ($st -eq 'idle' -and $stableEnough -and ($rt.sawWorking -or $elapsed -ge ($idleStableSeconds * 2))) {
        Write-Info "Lane $laneId ($label): complete step $stepId ($stepHuman/$stepCount)"
        if (-not $DryRun) {
          $step.status = 'completed'
          $step | Add-Member -NotePropertyName completedAt -NotePropertyValue ((Get-Date).ToUniversalTime().ToString('o')) -Force
          $dirty = $true
        }
        Write-SupervisorLog -JsonlPath $logPaths.Jsonl -MdPath $logPaths.Md -Event @{
          action    = 'step_completed'
          laneId    = $laneId
          laneLabel = $label
          surfaceId = $surfaceId
          stepId    = $stepId
          detail    = "marked completed after idle (sawWorking=$($rt.sawWorking))"
        }
        $rt.sawWorking = $false
        $rt.inProgressSince = $null
        $rt.lastState = $st
        # Fall through same cycle to dispatch next pending if still idle.
        $next = Get-NextStep $lane
        if (-not $next) { continue }
        $step = $next.Step
        $stepId = [string]$step.id
        $status = [string]$step.status
        $stepHuman = $next.Index + 1
      } else {
        $rt.lastState = $st
        continue
      }
    }

    if ($status -ne 'pending') {
      $rt.lastState = $st
      continue
    }

    if (-not (Test-MayDispatch -SurfaceState $surf -AllowUnknownState:$AllowUnknown)) {
      if ($st -ne $rt.lastState) {
        Write-Info "Lane $laneId ($label): wait (state=$st) before step $stepId"
      }
      $rt.lastState = $st
      continue
    }

    # Avoid double-dispatch: require surface to stay idle across grace after previous send.
    if ($rt.lastDispatchAt) {
      $sinceDispatch = ([datetime]::UtcNow - [datetime]$rt.lastDispatchAt).TotalSeconds
      if ($sinceDispatch -lt $idleStableSeconds) {
        $rt.lastState = $st
        continue
      }
    }

    $text = Build-InjectedPrompt -Plan $plan -Lane $lane -Step $step -StepIndex $stepHuman -StepCount $stepCount
    Write-Info "Lane $laneId ($label): DISPATCH step $stepId ($stepHuman/$stepCount) → $surfaceId"
    Write-SupervisorLog -JsonlPath $logPaths.Jsonl -MdPath $logPaths.Md -Event @{
      action    = $(if ($DryRun) { 'dispatch_dry_run' } else { 'dispatch' })
      laneId    = $laneId
      laneLabel = $label
      surfaceId = $surfaceId
      stepId    = $stepId
      detail    = ($(if ($step.title) { [string]$step.title } else { 'prompt' }) + " | chars=$($text.Length)")
      prompt    = $text
    }

    if (-not $DryRun) {
      try {
        Send-StepToSurface -SurfaceId $surfaceId -Text $text -SubmitEnter:$submitEnter
        $step.status = 'in_progress'
        $step | Add-Member -NotePropertyName dispatchedAt -NotePropertyValue ((Get-Date).ToUniversalTime().ToString('o')) -Force
        $dirty = $true
        $rt.inProgressSince = [datetime]::UtcNow
        $rt.sawWorking = $false
        $rt.lastDispatchAt = [datetime]::UtcNow
      } catch {
        Write-Warning "Lane ${laneId}: send failed: $_"
        Write-SupervisorLog -JsonlPath $logPaths.Jsonl -MdPath $logPaths.Md -Event @{
          action    = 'dispatch_error'
          laneId    = $laneId
          laneLabel = $label
          surfaceId = $surfaceId
          stepId    = $stepId
          detail    = "$_"
        }
      }
    }

    $rt.lastState = $st
  }

  if ($dirty -and -not $DryRun) {
    Save-JsonObject $plan $PlanPath
  }

  if ($OpenLogSurface -and -not $DryRun -and ($cycle % 3 -eq 0)) {
    try {
      # Best-effort refresh if a markdown surface was already bound to this file by the user/session.
      # `markdown <file>` creates/loads; repeated calls are acceptable for a log view.
    } catch { }
  }

  $allDone = $true
  foreach ($lane in @($plan.lanes)) {
    if ($null -ne $lane.enabled -and -not [bool]$lane.enabled) { continue }
    if (Get-NextStep $lane) { $allDone = $false; break }
  }
  if ($allDone) {
    Write-Info 'All enabled lanes complete — supervisor exit.'
    Write-SupervisorLog -JsonlPath $logPaths.Jsonl -MdPath $logPaths.Md -Event @{
      action    = 'exit'
      laneId    = '-'
      laneLabel = '-'
      surfaceId = '-'
      stepId    = '-'
      detail    = 'all lanes complete'
    }
    break
  }

  if ($Once) { break }
  Start-Sleep -Seconds $pollSeconds
}
