import {
  activeProjectGoal,
  activeProjectSubgoals,
  projectAcceptedRequirementsVersion,
  projectAuthorizationVersion,
  projectOrientationReady,
  projectRequirementsVersion,
  projectWorkItemReady,
  type ProjectManagerSession,
  type ProjectSupervisorContract,
  type ProjectTaskBatch,
  type ProjectTaskBatchCoverage,
  type ProjectWorkItem,
} from '../../shared/project-manager';

export interface ProjectExecutionIdentity {
  projectId: string;
  goalId: string;
  workItemId: string;
  requirementsVersion: number;
  authorizationVersion: number;
}

/** A revision-scoped identity regenerated by the control plane for every dispatched work item. */
export function buildProjectExecutionIdentityBlock(identity: ProjectExecutionIdentity): string {
  return [
    '[项目执行身份｜控制层已绑定]',
    `项目：${identity.projectId}`,
    `主目标：${identity.goalId}`,
    `工作项：${identity.workItemId}`,
    `需求版本：R${identity.requirementsVersion}`,
    `授权版本：A${identity.authorizationVersion}`,
    '这是本轮唯一有效的运行身份。新建、恢复或切换工作项时均以本块为准；旧终端、旧运行通道和旧对话身份只作审计历史，不得尝试恢复、等待或反复论证。',
  ].join('\n');
}

export function isProjectTargetedTestCommand(command: string): boolean {
  return /^\s*(?:(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?(?:test(?::[^\s]+)?|vitest|jest)|npx\s+(?:vitest|jest)|python(?:\.exe)?\s+-m\s+pytest|pytest|vitest|jest|cargo\s+test|go\s+test|dotnet\s+test|ctest|mvn\s+test|(?:gradle|gradlew|\.\/gradlew)\s+test)\b/i.test(command);
}

function normalizedCommand(value: string): string {
  return value.trim().toLowerCase().replace(/["'`]/gu, '').replace(/\s+/gu, ' ');
}

function unsafePermissionCommandReason(command: string): string | null {
  if (/[\r\n;&|<>`]/u.test(command) || command.includes('$(')) {
    return '权限命令包含 shell 链接、重定向或命令替换';
  }
  if (/\b(?:(?:powershell|pwsh)(?:\.exe)?\s+[^\r\n]{0,120}?-(?:e|enc|encodedcommand|command)|cmd(?:\.exe)?\s+\/c|(?:bash|sh|wsl(?:\.exe)?)\s+-c)\b/iu.test(command)) {
    return '权限命令包含可绕过测试边界的解释器入口';
  }
  return null;
}

export function commandMatchesAuthorizedPrefix(command: string, prefixes: readonly string[]): boolean {
  if (unsafePermissionCommandReason(command)) return false;
  const candidate = normalizedCommand(command);
  return prefixes.some((prefix) => {
    const allowed = normalizedCommand(prefix);
    return allowed.length >= 2 && (candidate === allowed || candidate.startsWith(`${allowed} `));
  });
}

/** Low-risk permission confirmation is on by default but remains command-scoped and fail-closed. */
export function projectPermissionAuthorizationError(
  contract: ProjectSupervisorContract,
  command: string,
): string | null {
  if (!contract.authority.permissionConfirm) {
    return '任务契约未授权监督 AI 自动确认权限';
  }
  const unsafeReason = unsafePermissionCommandReason(command);
  if (unsafeReason) return unsafeReason;
  if (isProjectTargetedTestCommand(command)) {
    if (!contract.authority.targetedTests) return '任务契约未授权监督 AI 运行测试';
    const prefixes = contract.authority.allowedCommandPrefixes || [];
    return prefixes.length === 0 || commandMatchesAuthorizedPrefix(command, prefixes)
      ? null
      : '测试命令不在任务契约 allowedCommandPrefixes 授权范围内';
  }
  return commandMatchesAuthorizedPrefix(command, contract.authority.allowedCommandPrefixes || [])
    ? null
    : '权限命令不在任务契约 allowedCommandPrefixes 授权范围内';
}

function projectTaskBatchStrings(value: unknown, limit: number): string[] {
  return Array.isArray(value)
    ? value.map((entry) => String(entry).trim().slice(0, 2_000)).filter(Boolean).slice(0, limit)
    : [];
}

function projectTaskBatchIdentity(value: string): string {
  return value.toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu, '');
}

export const TASK_VALIDATION_REPORTING_POLICY = [
  '验证结果无论通过、失败还是当前无法取得，都必须如实记录和报告，不得为了得到通过结果而隐瞒、筛选、改写或伪造结果。',
  '验证失败后，若能在当前成果、项目规则和风险边界内合理修正并形成新证据，可自主修正并重新验证；若失败本身是有效实验结果、当前条件无法解决、继续需要扩大范围或授权，或者继续尝试不会产生新证据，应结束本轮并如实返回。',
  '返回验证失败或无法验证时，说明实际结果、已有证据、影响、尚未满足的完成定义、已知原因或未知项，以及后续验证或继续工作所需条件。允许返回失败或无法验证，不代表完成定义已经满足。',
].join('');

export const PROJECT_TASK_EVIDENCE_ARTIFACT_POLICY = '项目成果验收需要可复核的实际证据文件。执行构建、运行、测试或测量时，按当前项目已有规范将关键命令、退出状态、实际结果和必要环境写入项目内持久证据文件，并在返回中列出项目内相对路径；不得只在最终回复中列出哈希或概括结论。项目规则不允许写入或当前无法形成文件时，如实说明原因和未验证项。';

export function renderProjectTaskWorkMode(
  taskWorkMode: 'single-thread' | 'multi-thread',
): string {
  return taskWorkMode === 'multi-thread'
    ? '[执行模式] 多线程：本批成果使用主线程和必要的内部子线程或子代理并行处理，同时运行的内部子线程或子代理不得超过 3 个。具体拆分、线程职责和整合方式根据项目事实自行决定；共享写入、共享资源和最终集成必须由主线程串行处理。若无法安全拆分，应停止并说明具体冲突。'
    : '[执行模式] 单线程：本批成果由当前主线程串行执行，不创建内部子线程或子代理。单线程仅限制并发组织，不限制在同一轮内连续完成多个必要步骤、文件修改、命令、测试、修正和验证。';
}

export function isCurrentProjectTaskBatch(value: unknown): value is ProjectTaskBatch {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return false;
  const raw = value as Record<string, unknown>;
  const allowedFields = new Set([
    'kind', 'coverage', 'outcome', 'completionDefinition', 'evidenceExpectations',
    'unmetCompletionItems', 'knownFacts', 'constraints', 'nonGoals',
  ]);
  return ['task', 'diagnostic', 'rework'].includes(String(raw.kind || ''))
    && ['whole-item', 'bounded-batch'].includes(String(raw.coverage || ''))
    && typeof raw.outcome === 'string'
    && raw.outcome.trim().length > 0
    && Object.keys(raw).every((field) => allowedFields.has(field))
    && ['completionDefinition', 'evidenceExpectations', 'unmetCompletionItems', 'knownFacts', 'constraints', 'nonGoals']
      .every((field) => Array.isArray(raw[field]) && (raw[field] as unknown[]).every((entry) => typeof entry === 'string'))
    && (raw.completionDefinition as string[]).some((entry) => entry.trim().length > 0);
}

export function projectTaskImplementationDirectiveError(value: string): string | null {
  const implementationDirective = /(?:必须|请)(?:修改|编辑|创建|删除).{0,120}(?:[\\/]|\.(?:ts|tsx|js|jsx|py|rs|go|java|cpp|h|md)\b)|(?:必须|请)(?:运行|执行).{0,120}\b(?:npm|pnpm|yarn|git|python|cargo|go|dotnet)\b|(?:必须|请)使用.{0,50}(?:技能|skill|框架|依赖|库)\b|\b(?:selectedRoute|expectedPaths|targetedValidation)\b/iu.test(value)
    || /\b(?:(?:you\s+)?(?:must|should)|please|required\s+to)\s+(?:edit|modify|create|delete|remove)\b.{0,120}(?:[\\/]|\.(?:ts|tsx|js|jsx|py|rs|go|java|cpp|h|md)\b)/iu.test(value)
    || /\b(?:run|execute)\s+(?:npm|pnpm|yarn|git|python|pytest|cargo|go|dotnet)\b/iu.test(value)
    || /\b(?:use|invoke)\s+(?:the\s+)?[^\r\n]{0,50}\b(?:skill|framework|dependency|library)\b/iu.test(value)
    || /\b(?:follow|use)\s+(?:the\s+)?(?:selected|specified|supervisor['’]s?)?\s*(?:implementation\s+)?(?:route|plan)\b/iu.test(value);
  return implementationDirective
    ? '成果批次只能描述结果、完成定义、证据期望、事实和约束，不能指定文件、命令、技能或实现路线'
    : null;
}

export function normalizeProjectTaskBatch(
  value: unknown,
  workItem: Pick<ProjectWorkItem, 'complexityAssessment' | 'contract'>,
  options: { allowUnmetCompletionItems?: boolean } = {},
): { batch?: ProjectTaskBatch; error?: string } {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return { error: '项目成果批次必须是 JSON 对象' };
  }
  const raw = value as Record<string, unknown>;
  const allowedFields = new Set([
    'kind', 'coverage', 'outcome', 'completionDefinition', 'evidenceExpectations',
    'unmetCompletionItems', 'knownFacts', 'constraints', 'nonGoals',
  ]);
  const unknownFields = Object.keys(raw).filter((field) => !allowedFields.has(field));
  if (unknownFields.length > 0) {
    return { error: `项目成果批次包含未授权字段：${unknownFields.join('、')}` };
  }
  const invalidArrayField = [
    'completionDefinition', 'evidenceExpectations', 'unmetCompletionItems',
    'knownFacts', 'constraints', 'nonGoals',
  ].find((field) => raw[field] !== undefined && (
    !Array.isArray(raw[field])
    || (raw[field] as unknown[]).some((entry) => typeof entry !== 'string')
  ));
  if (invalidArrayField) {
    return { error: `项目成果批次 ${invalidArrayField} 必须是字符串数组` };
  }
  const kind = String(raw.kind || '').trim();
  const coverage = String(raw.coverage || '').trim();
  const outcome = String(raw.outcome || '').trim().slice(0, 4_000);
  const completionDefinition = projectTaskBatchStrings(raw.completionDefinition, 50);
  const evidenceExpectations = projectTaskBatchStrings(raw.evidenceExpectations, 10);
  const unmetCompletionItems = projectTaskBatchStrings(raw.unmetCompletionItems, 10);
  const knownFacts = projectTaskBatchStrings(raw.knownFacts, 10);
  const constraints = projectTaskBatchStrings(raw.constraints, 10);
  const nonGoals = projectTaskBatchStrings(raw.nonGoals, 8);
  if (!['task', 'diagnostic', 'rework'].includes(kind)) {
    return { error: '项目成果批次 kind 必须是 task、diagnostic 或 rework' };
  }
  if (!['whole-item', 'bounded-batch'].includes(coverage)) {
    return { error: '项目成果批次 coverage 必须是 whole-item 或 bounded-batch' };
  }
  if (!outcome || completionDefinition.length === 0) {
    return { error: '项目成果批次必须包含 outcome 和非空 completionDefinition' };
  }
  if (coverage === 'bounded-batch' && completionDefinition.length > 3) {
    return { error: '单个 bounded-batch 最多包含 3 个完成定义；请缩小本批成果' };
  }
  if (unmetCompletionItems.length > 0
    && !options.allowUnmetCompletionItems) {
    return { error: '首次派遣不能包含 unmetCompletionItems；只有已有执行证据后的续作或返工才能列出本轮未通过项' };
  }
  if (coverage === 'whole-item') {
    if (workItem.complexityAssessment.complexity !== 'low'
      || workItem.complexityAssessment.decision !== 'single-task') {
      return { error: '只有项目 AI 已判定为 low 的原子工作项才能整项派发；当前工作项必须使用 bounded-batch' };
    }
    if (projectTaskBatchIdentity(outcome) !== projectTaskBatchIdentity(workItem.contract.objective)) {
      return { error: 'whole-item 的 outcome 必须与项目 AI 已确认的工作项成果一致，监督 AI 不能改写成果目标' };
    }
    const batchCriteria = new Set(completionDefinition.map(projectTaskBatchIdentity));
    const missingCriteria = workItem.contract.stopWhen
      .find((criterion) => !batchCriteria.has(projectTaskBatchIdentity(criterion)));
    if (missingCriteria) {
      return { error: `whole-item 的完成定义必须覆盖工作项全部停止条件，当前缺少：${missingCriteria}` };
    }
  }
  const taskFields = [
    outcome, ...completionDefinition, ...evidenceExpectations, ...unmetCompletionItems,
    ...knownFacts, ...constraints, ...nonGoals,
  ];
  const disclosureError = projectTaskInstructionDisclosureError(taskFields.join('\n'));
  if (disclosureError) return { error: disclosureError };
  const implementationDirectiveError = projectTaskImplementationDirectiveError([
    outcome, ...completionDefinition, ...evidenceExpectations, ...constraints, ...nonGoals,
  ].join('\n'));
  if (implementationDirectiveError) return { error: implementationDirectiveError };
  if (taskFields.join('\n').length > 16_000) {
    return { error: '项目成果批次内容超过 16000 字符；请只保留当前成果所需事实和边界' };
  }
  return {
    batch: {
      kind: kind as ProjectTaskBatch['kind'],
      coverage: coverage as ProjectTaskBatchCoverage,
      outcome,
      completionDefinition,
      evidenceExpectations,
      unmetCompletionItems,
      knownFacts,
      constraints,
      nonGoals,
    },
  };
}

export function renderProjectTaskBatch(
  contract: ProjectSupervisorContract,
  batch: ProjectTaskBatch,
  taskWorkMode: 'single-thread' | 'multi-thread' = 'single-thread',
): string {
  return [
    '[成果任务]',
    `成果方向：${contract.objective}`,
    `本批成果：${batch.outcome}`,
    contract.preconditions.length > 0 ? `前置条件：\n${contract.preconditions.map((item) => `- ${item}`).join('\n')}` : '',
    `完成定义：\n${batch.completionDefinition.map((item) => `- ${item}`).join('\n')}`,
    batch.evidenceExpectations.length > 0 ? `证据期望（如适用）：\n${batch.evidenceExpectations.map((item) => `- ${item}`).join('\n')}` : '',
    batch.unmetCompletionItems.length > 0 ? `本轮未通过项：\n${batch.unmetCompletionItems.map((item) => `- ${item}`).join('\n')}` : '',
    batch.knownFacts.length > 0 ? `已知现状（请先核对）：\n${batch.knownFacts.map((item) => `- ${item}`).join('\n')}` : '',
    batch.knownFacts.length > 0 ? '以上现状如与项目代码或实际状态不符，以项目事实为准并在结果中说明。' : '',
    batch.constraints.length > 0 ? `硬边界：\n${batch.constraints.map((item) => `- ${item}`).join('\n')}` : '',
    batch.nonGoals.length > 0 ? `本批不要求交付：\n${batch.nonGoals.map((item) => `- ${item}`).join('\n')}` : '',
    '开始前读取并严格遵循当前目录层级适用的 AGENTS、项目技能和仓库规范；若本任务与项目规范冲突，以项目规范为准。',
    '自行决定实现路线、必要的相邻修改、文件、命令、测试、技能和任务内部组织方式；本批不要求交付的内容不限制完成当前成果所必需的支持性工作。',
    `自行选择与风险相称的验证方式。${TASK_VALIDATION_REPORTING_POLICY}`,
    PROJECT_TASK_EVIDENCE_ARTIFACT_POLICY,
    renderProjectTaskWorkMode(taskWorkMode),
    '达到完成定义，或遇到真实阻塞、约束冲突、授权边界时结束本轮；如实报告成果、实际修改、已有证据、未验证项、剩余工作和阻塞。',
  ].filter(Boolean).join('\n\n');
}

const PROJECT_ORCHESTRATION_DISCLOSURES = [
  /任务\s*AI|项目\s*AI|项目管理\s*AI|监督\s*AI|专属监督(?:\s*AI)?|辅助任务\s*AI|辅助\s*AI|项目\s*ID|工作项\s*ID|\blane\b|控制层/iu,
  /\btask\s+ai\b|\bproject\s+ai\b|\bproject\s+manager\s+ai\b|\b(?:dedicated|project)\s+supervisor(?:\s+ai)?\b|\bsupervisor\s+ai\b|\bcontrol\s+plane\b|\bauxiliary(?:\s+task)?\s+ai\b|\b(?:project|work\s*item)\s+id\b/iu,
  /\b(?:ask|notify|follow|wait\s+for|coordinate\s+with|escalate\s+to|report(?:\s+back)?\s+to)\s+(?:your\s+|the\s+)?(?:project\s+manager|supervisor)\b/iu,
  /\b(?:project\s+manager|supervisor)['’]s\s+(?:plan|instructions?|decision|approval)\b/iu,
];

export function projectTaskInstructionDisclosureError(instruction: string): string | null {
  const normalized = instruction.trim();
  const disclosure = PROJECT_ORCHESTRATION_DISCLOSURES
    .map((pattern) => normalized.match(pattern)?.[0])
    .find(Boolean);
  return disclosure
    ? `任务 AI 指令不能暴露内部编排身份或路由信息：${disclosure}`
    : null;
}

export function projectTaskContractDisclosureError(
  contract: Pick<ProjectSupervisorContract, 'objective' | 'description' | 'preconditions' | 'stopWhen' | 'validation'>,
): string | null {
  const fields: Array<[string, string]> = [
    ['objective', contract.objective],
    ['description', contract.description],
    ...contract.preconditions.map((value) => ['preconditions', value] as [string, string]),
    ...contract.stopWhen.map((value) => ['stopWhen', value] as [string, string]),
    ...contract.validation.map((value) => ['validation', value] as [string, string]),
  ];
  for (const [field, value] of fields) {
    const error = projectTaskInstructionDisclosureError(value);
    if (error) return `任务合同 ${field} 不能进入任务 AI：${error}`;
  }
  return null;
}

export function projectDependencyError(items: readonly ProjectWorkItem[]): string | null {
  const byId = new Map(items.map((item) => [item.id, item]));
  if (byId.size !== items.length) return '任务 ID 不能重复';
  for (const item of items) {
    const missing = item.dependencies.find((dependency) => !byId.has(dependency));
    if (missing) return `任务 ${item.id} 依赖不存在的任务 ${missing}`;
    if (item.dependencies.includes(item.id)) return `任务 ${item.id} 不能依赖自身`;
  }

  const visiting = new Set<string>();
  const visited = new Set<string>();
  const visit = (id: string): boolean => {
    if (visiting.has(id)) return true;
    if (visited.has(id)) return false;
    visiting.add(id);
    const item = byId.get(id);
    if (item?.dependencies.some(visit)) return true;
    visiting.delete(id);
    visited.add(id);
    return false;
  };
  return items.some((item) => visit(item.id)) ? '任务依赖不能形成循环' : null;
}

export function readyProjectWorkItems(session: ProjectManagerSession): ProjectWorkItem[] {
  if (session.status !== 'active') return [];
  const activeGoalId = activeProjectGoal(session).id;
  return session.workItems.filter((item) => (
    item.goalId === activeGoalId
    && item.requirementsVersion === projectRequirementsVersion(session)
    && item.authorizationVersion === projectAuthorizationVersion(session)
    && !projectWorkItemSubgoalDependencyError(session, item)
    && projectWorkItemReady(item, session.workItems)
  ));
}

export type ProjectProgressObligationKind =
  | 'align-requirements'
  | 'sync-progress'
  | 'orient-project'
  | 'reconcile-stale-work'
  | 'plan-work'
  | 'resume-project'
  | 'dispatch-work'
  | 'recover-work'
  | 'validate-work'
  | 'resolve-decision'
  | 'resume-paused'
  | 'resolve-dependencies'
  | 'complete-goal';

export function projectWorkItemVerificationDeferred(
  session: ProjectManagerSession,
  item: ProjectWorkItem,
): boolean {
  const decision = item.verificationDecision;
  if (!decision) return false;
  return ['defer-verification', 'skip-verification'].includes(decision.action)
    && decision.requirementsVersion === projectRequirementsVersion(session)
    && decision.authorizationVersion === projectAuthorizationVersion(session);
}

export interface ProjectProgressObligation {
  kind: ProjectProgressObligationKind;
  summary: string;
  workItemId?: string;
}

export function projectHasRunnableGoalPlan(session: ProjectManagerSession): boolean {
  return activeProjectSubgoals(session).some((subgoal) => (
    subgoal.status === 'planned' || subgoal.status === 'active'
  ));
}

function projectAlignmentConfirmedAfterLatestRequirement(session: ProjectManagerSession): boolean {
  let latestRequired = -1;
  let latestConfirmed = -1;
  session.events.forEach((event, index) => {
    if (event.kind === 'requirements-alignment-required') latestRequired = index;
    if (event.kind === 'requirements-alignment-confirmed') latestConfirmed = index;
  });
  return latestRequired >= 0 && latestConfirmed > latestRequired;
}

/**
 * Describe the next project-owned action when no dedicated supervisor lane is
 * active. This is intentionally pure so the runtime watchdog and tests use the
 * same liveness invariant.
 */
export function projectProgressObligation(
  session: ProjectManagerSession,
): ProjectProgressObligation | null {
  if (!['active', 'waiting'].includes(session.status)
    || session.pendingUserQuestion
    || (session.pendingSupervisorTransitions || []).length > 0) {
    return null;
  }
  const activeGoal = activeProjectGoal(session);
  // A completed goal intentionally waits for the user to define the next goal.
  // It is not an internal liveness obligation and must not be auto-resumed.
  if (session.status === 'waiting' && activeGoal.status === 'achieved') return null;
  const alignmentConfirmedWhileWaiting = session.status === 'waiting'
    && projectAlignmentConfirmedAfterLatestRequirement(session);
  if (projectAcceptedRequirementsVersion(session) !== projectRequirementsVersion(session)
    && !alignmentConfirmedWhileWaiting) {
    return { kind: 'align-requirements', summary: '当前需求版本尚未完成项目对齐，不能继续使用旧合同或保持静默' };
  }
  if (session.progressSync?.status === 'review-required') {
    return { kind: 'sync-progress', summary: '项目外部进度尚未复核，需要先同步当前工作区事实再继续派发' };
  }
  if (!projectOrientationReady(session)) {
    return { kind: 'orient-project', summary: '项目认知基线尚未绑定当前需求、授权和目录快照，需要先复核现状再规划或派发' };
  }
  const activeGoalItems = session.workItems.filter((item) => (
    item.goalId === activeGoal.id && item.status !== 'stopped'
  ));
  const currentItems = activeGoalItems.filter((item) => (
    item.requirementsVersion === projectRequirementsVersion(session)
    && item.authorizationVersion === projectAuthorizationVersion(session)
  ));
  const staleOpenItems = activeGoalItems.filter((item) => (
    item.status !== 'completed'
    && (item.requirementsVersion !== projectRequirementsVersion(session)
      || item.authorizationVersion !== projectAuthorizationVersion(session))
  ));
  if (staleOpenItems.length > 0) {
    return {
      kind: 'reconcile-stale-work',
      summary: '当前主目标仍有旧需求或旧授权版本工作项，需要重绑、停止或替换，不能另建重复任务',
    };
  }
  if (session.status === 'waiting') {
    if (!projectHasRunnableGoalPlan(session)) {
      return { kind: 'plan-work', summary: '当前主目标尚未建立阶段计划，需要先保存新版本阶段计划再恢复项目' };
    }
    return { kind: 'resume-project', summary: '目标变更后的需求、认知和阶段计划门禁已经完成，需要显式恢复项目再继续创建或派发任务' };
  }
  if (currentItems.length === 0) {
    return { kind: 'plan-work', summary: '当前主目标尚无执行工作项，需要规划并派发第一个完整阶段成果' };
  }
  const validating = currentItems.find((item) => item.status === 'validating');
  if (validating) {
    return { kind: 'validate-work', workItemId: validating.id, summary: `工作项 ${validating.id} 等待项目级验收或补证方向` };
  }
  const running = currentItems.find((item) => item.status === 'running');
  if (running) {
    return { kind: 'recover-work', workItemId: running.id, summary: `工作项 ${running.id} 仍标记运行中，但没有活动监督链，需要恢复或重建` };
  }
  const ready = currentItems.find((item) => (
    !projectWorkItemSubgoalDependencyError(session, item)
    && projectWorkItemReady(item, currentItems)
  ));
  if (ready) {
    return { kind: 'dispatch-work', workItemId: ready.id, summary: `工作项 ${ready.id} 已满足依赖，需要派发专属监督链` };
  }
  const decision = currentItems.find((item) => (
    (item.status === 'waiting-decision' || item.status === 'failed')
    && !projectWorkItemVerificationDeferred(session, item)
  ));
  if (decision) {
    return { kind: 'resolve-decision', workItemId: decision.id, summary: `工作项 ${decision.id} 等待项目 AI 裁决、重规划或暂缓` };
  }
  const paused = currentItems.find((item) => (
    item.status === 'paused' && !projectWorkItemVerificationDeferred(session, item)
  ));
  if (paused) {
    return { kind: 'resume-paused', workItemId: paused.id, summary: `工作项 ${paused.id} 已暂缓；需要恢复、改派独立工作或向用户升级真实阻塞` };
  }
  if (currentItems.every((item) => item.status === 'completed')) {
    const uncoveredSubgoal = activeProjectSubgoals(session).find((subgoal) => (
      !['achieved', 'obsolete'].includes(subgoal.status)
    ));
    if (uncoveredSubgoal) {
      return {
        kind: 'plan-work',
        summary: `阶段 ${uncoveredSubgoal.title}（${uncoveredSubgoal.id}）尚未完成且没有开放工作项，需要按当前协议创建后继工作项并派发监督`,
      };
    }
    return { kind: 'complete-goal', summary: '当前主目标的工作项均已完成，需要执行目标级验收或关闭主目标' };
  }
  return {
    kind: 'resolve-dependencies',
    summary: '当前没有可派发工作项，但仍有未完成依赖；需要修正阶段/任务依赖或明确暂缓路径',
  };
}

/** A task may run after coarse dependencies close or the user explicitly defers their verification. */
export function projectWorkItemSubgoalDependencyError(
  session: ProjectManagerSession,
  item: ProjectWorkItem,
): string | null {
  const subgoals = activeProjectSubgoals(session);
  const subgoal = subgoals.find((candidate) => candidate.id === item.subgoalId);
  if (!subgoal) return '任务没有有效的当前阶段目标';
  const byId = new Map(subgoals.map((candidate) => [candidate.id, candidate]));
  const incomplete = subgoal.dependencies.find((dependencyId) => {
    const dependency = byId.get(dependencyId);
    const dependencyItems = session.workItems.filter((candidate) => (
      candidate.goalId === item.goalId && candidate.subgoalId === dependencyId
    ));
    const verificationDeferred = dependencyItems.some((candidate) => (
      projectWorkItemVerificationDeferred(session, candidate)
    )) && dependencyItems.every((candidate) => (
      candidate.status === 'completed' || projectWorkItemVerificationDeferred(session, candidate)
    ));
    return !dependency || (!['achieved', 'obsolete'].includes(dependency.status) && !verificationDeferred);
  });
  return incomplete
    ? `阶段目标 ${subgoal.id} 依赖尚未完成：${incomplete}`
    : null;
}

export type ProjectCompletionState = 'in-progress' | 'blocked' | 'ready-for-validation' | 'completed';

export function projectArtifactLocationViolation(value: string): string | null {
  return sharedProjectArtifactLocationViolation(value);
}

export function projectArtifactCommandViolation(value: string): string | null {
  const trimmed = value.trim();
  if (/^(?:get-content|get-filehash|test-path|select-string|rg|fd|type|cat)\b/iu.test(trimmed)) {
    return null;
  }
  const quotedCandidates = [...value.matchAll(/["']([^"']*(?:\.project-plans|runs|run[-_]templates|tests?|src)[\\/][^"']+)["']/giu)]
    .map((match) => match[1]);
  const candidates = [...quotedCandidates, ...value.split(/\s+/u)]
    .map((entry) => entry.replace(/^["'`([{<]+|["'`\])}>;,]+$/gu, ''))
    .filter((entry) => /(?:\.project-plans|runs|run[-_]templates|tests?|src)[\\/]/iu.test(entry));
  for (const rawCandidate of candidates) {
    const pathOffset = rawCandidate.search(/\.project-plans[\\/]|runs[\\/]|run[-_]templates[\\/]|(?:tests?|src)[\\/]/iu);
    const candidate = pathOffset >= 0
      ? rawCandidate.slice(pathOffset)
      : rawCandidate;
    const violation = projectArtifactLocationViolation(candidate);
    if (violation) return violation;
  }
  return null;
}

/** Enforce the parts of a project contract that can be proven from a structured decision. */
export function projectContractViolation(
  _contract: ProjectSupervisorContract,
  proposal: {
    instruction?: string;
    command?: string;
    changedFiles?: string[];
    testCommand?: string;
    retry?: boolean;
    artifactAccess?: 'write' | 'read';
  },
): string | null {
  for (const file of proposal.changedFiles || []) {
    if (proposal.artifactAccess === 'read') continue;
    const violation = sharedProjectArtifactLocationViolation(file);
    if (violation) return violation;
  }
  return projectArtifactCommandViolation(proposal.command || proposal.instruction || '');
}
export function projectCompletionState(session: ProjectManagerSession): ProjectCompletionState {
  if (session.status === 'completed') return 'completed';
  const activeGoalId = activeProjectGoal(session).id;
  const required = session.workItems.filter((item) => item.goalId === activeGoalId && item.status !== 'stopped');
  if (required.length > 0 && required.every((item) => item.status === 'completed')) {
    return 'ready-for-validation';
  }
  const actionable = required.some((item) => (
    item.status === 'running'
    || item.status === 'validating'
    || projectWorkItemReady(item, required)
  ));
  const waiting = required.some((item) => (
    item.status === 'waiting-decision' || item.status === 'failed' || item.status === 'paused'
  ));
  return !actionable && waiting ? 'blocked' : 'in-progress';
}

export function buildProjectSupervisorBriefing(options: {
  workItemId: string;
  contract: ProjectSupervisorContract;
  taskWorkMode?: 'single-thread' | 'multi-thread';
  executionIdentity?: ProjectExecutionIdentity;
  projectGoal?: string;
  stage?: {
    title: string;
    outcome: string;
    acceptance: string[];
  };
}): string {
  return [
    '[项目监督任务｜当前协议] ' + options.workItemId,
    options.executionIdentity ? buildProjectExecutionIdentityBlock(options.executionIdentity) : '',
    options.projectGoal ? '项目总目标：' + options.projectGoal : '',
    options.stage ? '当前任务成果：' + options.stage.outcome + '\n验收：' + options.stage.acceptance.join('；') : '',
    '任务成果：' + options.contract.objective,
    options.contract.description ? '说明：' + options.contract.description : '',
    '停止与验收：' + [...options.contract.stopWhen, ...options.contract.validation].join('；'),
    '你是常驻监督和结果裁决者，不是项目执行者。不得修改项目文件、运行实现或测试命令、选择任务技能、规定具体实现路线，或代替任务 AI 做普通技术决策。',
    '你和项目 AI 默认拥有用户已确认目标内低风险、可逆的技术选择、聚焦测试、重试、小范围路线调整和安全权限判断裁量权；显式合同限制仍可收紧该权力。',
    '你先在当前工作项合同内直接决定 continue、rework 或 complete。只有需要改变总计划、跨任务协调、成果定义冲突或超出当前合同边界时，才使用 needs-human 上报项目 AI；由项目 AI 依据用户已确认计划决策，项目 AI 仍无法决定或涉及用户专属信息与授权时再向用户提问。禁止越级或把普通技术问题逐层上报。',
    '风险、不可逆、凭据、生产、外部访问及改变目标、范围或验收的事项必须先上报项目 AI，不得直接询问用户；项目 AI 能依据用户既有指令和授权决定时直接回执，只有仍无法决定时才继续询问用户。',
    '如果你认为用户的目标、范围、前置条件、验收或正式计划需要补充，禁止先按补充内容执行。使用 needs-human important + contract-change，一次提交待补充细节、影响、可选方案和推荐项；项目 AI 必须通过 project ask 取得用户确认并更新账本后才能重新派发。',
    `任务 AI 自主遵循目标项目的 AGENTS、技能和规范，并自行决定实现、测试与内部组织。工作项初始执行模式为 ${options.taskWorkMode === 'multi-thread' ? '多线程' : '单线程'}；你必须根据当前批次复杂度、独立成果和共享资源，在每次 continue/rework 时用 --task-work-mode single-thread|multi-thread 明确本批执行模式，不得替任务 AI 规划具体线程分工。`,
    'continue/rework 必须先把中性成果批次 JSON 写入当前监督隔离目录的 .wmux/tmp/<唯一文件名>.json，再通过 --task-file 提交，并通过 --task-work-mode 明确本批使用单线程还是多线程。字段只允许 kind、coverage、outcome、completionDefinition、evidenceExpectations、unmetCompletionItems、knownFacts、constraints、nonGoals；只有 outcome 和 completionDefinition 必填，其余字段没有真实内容时省略或传空数组。',
    '简单、强耦合或共享写入密集的批次使用 single-thread；存在两个及以上可独立推进成果的复杂批次使用 multi-thread。multi-thread 要求本批实际使用内部并行；无法安全拆分时应改用 single-thread，不得把“允许并行”当作已满足执行要求。',
    'completionDefinition 只说明做到什么程度可以结束当前批次，不规定验证方法；evidenceExpectations 可选，只有用户明确要求、项目规则要求或风险确实需要特定证据时才填写。验证通过、失败或当前无法取得都必须如实返回；能在当前边界内形成新证据时由任务 AI 自主修正并重验，有效失败、条件不足或继续不会产生新证据时应停止空耗。允许返回失败或无法验证，不代表完成定义已经满足。',
    'unmetCompletionItems 只用于已有执行证据后的续作或返工，首次派遣禁止填写。项目 AI 已判定为 low 且成果原子的工作项可使用 coverage=whole-item 整项派发，不得为了形式而强拆；其他情况使用 coverage=bounded-batch，每批只有一个成果且最多包含 3 个完成定义。',
    '你只描述当前批次需要形成的结果、完成定义、必要证据期望、已确认事实和约束，不向任务端注入项目/工作项身份、监督协议、路由预算、指定文件、命令、技能或实现路线；任务端始终只按目标项目规则和技能自主工作。',
    '只有出现忘记项目规则、重复已完成工作、连续矛盾、偏离当前成果，或同一阻塞连续两轮没有新证据时，才判定严重上下文污染。确认任务 AI 的 runDepth=0 后，使用 context-recovery 让控制层在原终端执行一次 /new 并重发中性成果包；同一工作项不得重复清空。',
    '完整成果满足后提交 complete；仍有任务内工作时直接 continue/rework，不得把微步骤交给项目 AI 或用户。',
  ].filter(Boolean).join('\n');
}
import {
  projectArtifactLocationViolation as sharedProjectArtifactLocationViolation,
} from '../../shared/project-artifact-policy';
