import {
  activeProjectGoal,
  activeProjectSubgoals,
  projectAcceptedRequirementsVersion,
  projectAuthorizationVersion,
  projectOrientationReady,
  projectRequirementsVersion,
  projectWorkItemReady,
  type ProjectManagerSession,
  type ProjectSupervisorContract,
  type ProjectWorkItem,
} from '../../shared/project-manager';

export interface ProjectExecutionIdentity {
  projectId: string;
  goalId: string;
  workItemId: string;
  requirementsVersion: number;
  authorizationVersion: number;
}

/** A revision-scoped identity regenerated by the control plane for every dispatched work item. */
export function buildProjectExecutionIdentityBlock(identity: ProjectExecutionIdentity): string {
  return [
    '[项目执行身份｜控制层已绑定]',
    `项目：${identity.projectId}`,
    `主目标：${identity.goalId}`,
    `工作项：${identity.workItemId}`,
    `需求版本：R${identity.requirementsVersion}`,
    `授权版本：A${identity.authorizationVersion}`,
    '这是本轮唯一有效的运行身份。新建、恢复或切换工作项时均以本块为准；旧终端、旧运行通道和旧对话身份只作审计历史，不得尝试恢复、等待或反复论证。',
  ].join('\n');
}

export function isProjectTargetedTestCommand(command: string): boolean {
  return /^\s*(?:(?:npm|pnpm|yarn|bun)\s+(?:run\s+)?(?:test(?::[^\s]+)?|vitest|jest)|npx\s+(?:vitest|jest)|python(?:\.exe)?\s+-m\s+pytest|pytest|vitest|jest|cargo\s+test|go\s+test|dotnet\s+test|ctest|mvn\s+test|(?:gradle|gradlew|\.\/gradlew)\s+test)\b/i.test(command);
}

function normalizedCommand(value: string): string {
  return value.trim().toLowerCase().replace(/["'`]/gu, '').replace(/\s+/gu, ' ');
}

export function commandMatchesAuthorizedPrefix(command: string, prefixes: readonly string[]): boolean {
  if (/[\r\n;&|<>`]/u.test(command) || command.includes('$(')) return false;
  const candidate = normalizedCommand(command);
  return prefixes.some((prefix) => {
    const allowed = normalizedCommand(prefix);
    return allowed.length >= 2 && (candidate === allowed || candidate.startsWith(`${allowed} `));
  });
}

/** Project permission confirmation is opt-in and command-scoped; project mode itself grants nothing. */
export function projectPermissionAuthorizationError(
  contract: ProjectSupervisorContract,
  command: string,
): string | null {
  if (!contract.authority.permissionConfirm) {
    return '任务契约未授权监督 AI 自动确认权限';
  }
  if (isProjectTargetedTestCommand(command)) {
    if (!contract.authority.targetedTests) return '任务契约未授权监督 AI 运行测试';
    const prefixes = contract.authority.allowedCommandPrefixes || [];
    return prefixes.length === 0 || commandMatchesAuthorizedPrefix(command, prefixes)
      ? null
      : '测试命令不在任务契约 allowedCommandPrefixes 授权范围内';
  }
  return commandMatchesAuthorizedPrefix(command, contract.authority.allowedCommandPrefixes || [])
    ? null
    : '权限命令不在任务契约 allowedCommandPrefixes 授权范围内';
}

export function buildProjectTaskExecutionEnvelope(
  contract: ProjectSupervisorContract,
  taskWorkMode: 'single-thread' | 'multi-thread' = 'single-thread',
): string {
  return [
    '[成果任务]',
    `目标：${contract.objective}`,
    contract.description ? `说明：${contract.description}` : '',
    contract.preconditions.length > 0 ? `前置条件：${contract.preconditions.join('；')}` : '',
    `验收条件：${[...contract.stopWhen, ...contract.validation].join('；')}`,
    '开始前读取并严格遵循当前目录层级适用的 AGENTS、项目技能和仓库规范；若任务描述与项目规范冲突，以项目规范为准。',
    '你自行决定实现路线、文件、命令、测试和技能；线程内的具体分工也由你决定，但必须遵守本成果包指定的执行模式。',
    taskWorkMode === 'multi-thread'
      ? '[执行模式] 多线程：使用主线程和必要的内部子线程推进，同时工作的内部子线程不得超过 3 个；共享写入、共享资源和最终集成必须串行。'
      : '[执行模式] 单线程：在当前主线程内完成任务，不创建内部子线程或执行子代理。',
    '持续推进到形成可验证成果、真实阻塞或用户授权边界，不要因内部微步骤完成而停顿，也不要等待外部逐步批准普通技术选择。',
    '删除或破坏性覆盖、外部访问、凭据、提权、发布、生产环境和真实硬件高风险操作仍须遵守项目规范及用户授权边界。',
    '结束本轮时简要报告成果、实际修改、验证结果、证据、剩余工作和真实阻塞。',
  ].filter(Boolean).join('\n');
}

export interface PreparedProjectTaskDelivery {
  action: string;
  delivery: string;
}

const PROJECT_ORCHESTRATION_DISCLOSURES = [
  /项目\s*AI|项目管理(?:\s*AI)?|监督\s*AI|专属监督(?:\s*AI)?|辅助任务\s*AI|辅助\s*AI|项目\s*ID|工作项\s*ID|\blane\b|控制层/iu,
  /\bproject\s+ai\b|\bproject\s+manager\s+ai\b|\b(?:dedicated|project)\s+supervisor(?:\s+ai)?\b|\bsupervisor\s+ai\b|\bcontrol\s+plane\b|\bauxiliary(?:\s+task)?\s+ai\b|\b(?:project|work\s*item)\s+id\b/iu,
  /\b(?:ask|notify|follow|wait\s+for|coordinate\s+with|escalate\s+to|report(?:\s+back)?\s+to)\s+(?:your\s+|the\s+)?(?:project\s+manager|supervisor)\b/iu,
  /\b(?:project\s+manager|supervisor)['’]s\s+(?:plan|instructions?|decision|approval)\b/iu,
];

export function projectTaskInstructionDisclosureError(instruction: string): string | null {
  const normalized = instruction.trim();
  const disclosure = PROJECT_ORCHESTRATION_DISCLOSURES
    .map((pattern) => normalized.match(pattern)?.[0])
    .find(Boolean);
  return disclosure
    ? `任务 AI 指令不能暴露内部编排身份或路由信息：${disclosure}`
    : null;
}

/** Keep the persisted contract authoritative while exposing only the executable action to guards. */
export function prepareProjectTaskDelivery(
  contract: ProjectSupervisorContract,
  instruction: string,
  contractPending: boolean,
  taskWorkMode: 'single-thread' | 'multi-thread' = 'single-thread',
  repeatWorkMode = false,
): PreparedProjectTaskDelivery {
  const requested = instruction.trim();
  if (!contractPending) {
    return {
      action: requested,
      delivery: repeatWorkMode
        ? `${taskWorkMode === 'multi-thread'
          ? '[执行模式] 多线程：使用主线程和必要的内部子线程推进，同时工作的内部子线程不得超过 3 个；共享写入、共享资源和最终集成必须串行。'
          : '[执行模式] 单线程：在当前主线程内完成任务，不创建内部子线程或执行子代理。'}\n${requested}`
        : requested,
    };
  }

  const envelope = buildProjectTaskExecutionEnvelope(contract, taskWorkMode);
  return {
    action: requested,
    delivery: requested
      ? `${envelope}\n\n[本轮执行指令]\n${requested}`
      : envelope,
  };
}

export function projectDependencyError(items: readonly ProjectWorkItem[]): string | null {
  const byId = new Map(items.map((item) => [item.id, item]));
  if (byId.size !== items.length) return '任务 ID 不能重复';
  for (const item of items) {
    const missing = item.dependencies.find((dependency) => !byId.has(dependency));
    if (missing) return `任务 ${item.id} 依赖不存在的任务 ${missing}`;
    if (item.dependencies.includes(item.id)) return `任务 ${item.id} 不能依赖自身`;
  }

  const visiting = new Set<string>();
  const visited = new Set<string>();
  const visit = (id: string): boolean => {
    if (visiting.has(id)) return true;
    if (visited.has(id)) return false;
    visiting.add(id);
    const item = byId.get(id);
    if (item?.dependencies.some(visit)) return true;
    visiting.delete(id);
    visited.add(id);
    return false;
  };
  return items.some((item) => visit(item.id)) ? '任务依赖不能形成循环' : null;
}

export function readyProjectWorkItems(session: ProjectManagerSession): ProjectWorkItem[] {
  if (session.status !== 'active') return [];
  const activeGoalId = activeProjectGoal(session).id;
  return session.workItems.filter((item) => (
    item.goalId === activeGoalId
    && item.requirementsVersion === projectRequirementsVersion(session)
    && item.authorizationVersion === projectAuthorizationVersion(session)
    && !projectWorkItemSubgoalDependencyError(session, item)
    && projectWorkItemReady(item, session.workItems)
  ));
}

export type ProjectProgressObligationKind =
  | 'align-requirements'
  | 'sync-progress'
  | 'orient-project'
  | 'reconcile-stale-work'
  | 'plan-work'
  | 'resume-project'
  | 'dispatch-work'
  | 'recover-work'
  | 'validate-work'
  | 'resolve-decision'
  | 'resume-paused'
  | 'resolve-dependencies'
  | 'complete-goal';

export interface ProjectProgressObligation {
  kind: ProjectProgressObligationKind;
  summary: string;
  workItemId?: string;
}

export function projectHasRunnableGoalPlan(session: ProjectManagerSession): boolean {
  return activeProjectSubgoals(session).some((subgoal) => (
    subgoal.status === 'planned' || subgoal.status === 'active'
  ));
}

function projectAlignmentConfirmedAfterLatestRequirement(session: ProjectManagerSession): boolean {
  let latestRequired = -1;
  let latestConfirmed = -1;
  session.events.forEach((event, index) => {
    if (event.kind === 'requirements-alignment-required') latestRequired = index;
    if (event.kind === 'requirements-alignment-confirmed') latestConfirmed = index;
  });
  return latestRequired >= 0 && latestConfirmed > latestRequired;
}

/**
 * Describe the next project-owned action when no dedicated supervisor lane is
 * active. This is intentionally pure so the runtime watchdog and tests use the
 * same liveness invariant.
 */
export function projectProgressObligation(
  session: ProjectManagerSession,
): ProjectProgressObligation | null {
  if (!['active', 'waiting'].includes(session.status)
    || session.pendingUserQuestion
    || (session.pendingSupervisorTransitions || []).length > 0) {
    return null;
  }
  const activeGoal = activeProjectGoal(session);
  // A completed goal intentionally waits for the user to define the next goal.
  // It is not an internal liveness obligation and must not be auto-resumed.
  if (session.status === 'waiting' && activeGoal.status === 'achieved') return null;
  const alignmentConfirmedWhileWaiting = session.status === 'waiting'
    && projectAlignmentConfirmedAfterLatestRequirement(session);
  if (projectAcceptedRequirementsVersion(session) !== projectRequirementsVersion(session)
    && !alignmentConfirmedWhileWaiting) {
    return { kind: 'align-requirements', summary: '当前需求版本尚未完成项目对齐，不能继续使用旧合同或保持静默' };
  }
  if (session.progressSync?.status === 'review-required') {
    return { kind: 'sync-progress', summary: '项目外部进度尚未复核，需要先同步当前工作区事实再继续派发' };
  }
  if (!projectOrientationReady(session)) {
    return { kind: 'orient-project', summary: '项目认知基线尚未绑定当前需求、授权和目录快照，需要先复核现状再规划或派发' };
  }
  const activeGoalItems = session.workItems.filter((item) => (
    item.goalId === activeGoal.id && item.status !== 'stopped'
  ));
  const currentItems = activeGoalItems.filter((item) => (
    item.requirementsVersion === projectRequirementsVersion(session)
    && item.authorizationVersion === projectAuthorizationVersion(session)
  ));
  const staleOpenItems = activeGoalItems.filter((item) => (
    item.status !== 'completed'
    && (item.requirementsVersion !== projectRequirementsVersion(session)
      || item.authorizationVersion !== projectAuthorizationVersion(session))
  ));
  if (staleOpenItems.length > 0) {
    return {
      kind: 'reconcile-stale-work',
      summary: '当前主目标仍有旧需求或旧授权版本工作项，需要重绑、停止或替换，不能另建重复任务',
    };
  }
  if (session.status === 'waiting') {
    if (!projectHasRunnableGoalPlan(session)) {
      return { kind: 'plan-work', summary: '当前主目标尚未建立阶段计划，需要先保存新版本阶段计划再恢复项目' };
    }
    return { kind: 'resume-project', summary: '目标变更后的需求、认知和阶段计划门禁已经完成，需要显式恢复项目再继续创建或派发任务' };
  }
  if (currentItems.length === 0) {
    return { kind: 'plan-work', summary: '当前主目标尚无执行工作项，需要规划并派发第一个完整阶段成果' };
  }
  const validating = currentItems.find((item) => item.status === 'validating');
  if (validating) {
    return { kind: 'validate-work', workItemId: validating.id, summary: `工作项 ${validating.id} 等待项目级验收或补证方向` };
  }
  const running = currentItems.find((item) => item.status === 'running');
  if (running) {
    return { kind: 'recover-work', workItemId: running.id, summary: `工作项 ${running.id} 仍标记运行中，但没有活动监督链，需要恢复或重建` };
  }
  const ready = currentItems.find((item) => (
    !projectWorkItemSubgoalDependencyError(session, item)
    && projectWorkItemReady(item, currentItems)
  ));
  if (ready) {
    return { kind: 'dispatch-work', workItemId: ready.id, summary: `工作项 ${ready.id} 已满足依赖，需要派发专属监督链` };
  }
  const decision = currentItems.find((item) => item.status === 'waiting-decision' || item.status === 'failed');
  if (decision) {
    return { kind: 'resolve-decision', workItemId: decision.id, summary: `工作项 ${decision.id} 等待项目 AI 裁决、重规划或暂缓` };
  }
  const paused = currentItems.find((item) => item.status === 'paused');
  if (paused) {
    return { kind: 'resume-paused', workItemId: paused.id, summary: `工作项 ${paused.id} 已暂缓；需要恢复、改派独立工作或向用户升级真实阻塞` };
  }
  if (currentItems.every((item) => item.status === 'completed')) {
    const uncoveredSubgoal = activeProjectSubgoals(session).find((subgoal) => (
      !['achieved', 'obsolete'].includes(subgoal.status)
    ));
    if (uncoveredSubgoal) {
      return {
        kind: 'plan-work',
        summary: `阶段 ${uncoveredSubgoal.title}（${uncoveredSubgoal.id}）尚未完成且没有开放工作项，需要按当前协议创建后继工作项并派发监督`,
      };
    }
    return { kind: 'complete-goal', summary: '当前主目标的工作项均已完成，需要执行目标级验收或关闭主目标' };
  }
  return {
    kind: 'resolve-dependencies',
    summary: '当前没有可派发工作项，但仍有未完成依赖；需要修正阶段/任务依赖或明确暂缓路径',
  };
}

/** A task may run only after every coarse stage dependency has been closed. */
export function projectWorkItemSubgoalDependencyError(
  session: ProjectManagerSession,
  item: ProjectWorkItem,
): string | null {
  const subgoals = activeProjectSubgoals(session);
  const subgoal = subgoals.find((candidate) => candidate.id === item.subgoalId);
  if (!subgoal) return '任务没有有效的当前阶段目标';
  const byId = new Map(subgoals.map((candidate) => [candidate.id, candidate]));
  const incomplete = subgoal.dependencies.find((dependencyId) => {
    const dependency = byId.get(dependencyId);
    return !dependency || !['achieved', 'obsolete'].includes(dependency.status);
  });
  return incomplete
    ? `阶段目标 ${subgoal.id} 依赖尚未完成：${incomplete}`
    : null;
}

export type ProjectCompletionState = 'in-progress' | 'blocked' | 'ready-for-validation' | 'completed';

export function projectArtifactLocationViolation(value: string): string | null {
  return sharedProjectArtifactLocationViolation(value);
}

export function projectArtifactCommandViolation(value: string): string | null {
  const trimmed = value.trim();
  if (/^(?:get-content|get-filehash|test-path|select-string|rg|fd|type|cat)\b/iu.test(trimmed)) {
    return null;
  }
  const quotedCandidates = [...value.matchAll(/["']([^"']*(?:\.project-plans|runs|run[-_]templates|tests?|src)[\\/][^"']+)["']/giu)]
    .map((match) => match[1]);
  const candidates = [...quotedCandidates, ...value.split(/\s+/u)]
    .map((entry) => entry.replace(/^["'`([{<]+|["'`\])}>;,]+$/gu, ''))
    .filter((entry) => /(?:\.project-plans|runs|run[-_]templates|tests?|src)[\\/]/iu.test(entry));
  for (const rawCandidate of candidates) {
    const pathOffset = rawCandidate.search(/\.project-plans[\\/]|runs[\\/]|run[-_]templates[\\/]|(?:tests?|src)[\\/]/iu);
    const candidate = pathOffset >= 0
      ? rawCandidate.slice(pathOffset)
      : rawCandidate;
    const violation = projectArtifactLocationViolation(candidate);
    if (violation) return violation;
  }
  return null;
}

/** Enforce the parts of a project contract that can be proven from a structured decision. */
export function projectContractViolation(
  _contract: ProjectSupervisorContract,
  proposal: {
    instruction?: string;
    command?: string;
    changedFiles?: string[];
    testCommand?: string;
    retry?: boolean;
    artifactAccess?: 'write' | 'read';
  },
): string | null {
  for (const file of proposal.changedFiles || []) {
    if (proposal.artifactAccess === 'read') continue;
    const violation = sharedProjectArtifactLocationViolation(file);
    if (violation) return violation;
  }
  return projectArtifactCommandViolation(proposal.command || proposal.instruction || '');
}
export function projectCompletionState(session: ProjectManagerSession): ProjectCompletionState {
  if (session.status === 'completed') return 'completed';
  const activeGoalId = activeProjectGoal(session).id;
  const required = session.workItems.filter((item) => item.goalId === activeGoalId && item.status !== 'stopped');
  if (required.length > 0 && required.every((item) => item.status === 'completed')) {
    return 'ready-for-validation';
  }
  const actionable = required.some((item) => (
    item.status === 'running'
    || item.status === 'validating'
    || projectWorkItemReady(item, required)
  ));
  const waiting = required.some((item) => (
    item.status === 'waiting-decision' || item.status === 'failed' || item.status === 'paused'
  ));
  return !actionable && waiting ? 'blocked' : 'in-progress';
}

export function buildProjectSupervisorBriefing(options: {
  workItemId: string;
  contract: ProjectSupervisorContract;
  taskWorkMode?: 'single-thread' | 'multi-thread';
  executionIdentity?: ProjectExecutionIdentity;
  projectGoal?: string;
  stage?: {
    title: string;
    outcome: string;
    acceptance: string[];
  };
}): string {
  return [
    '[项目监督任务｜P9] ' + options.workItemId,
    options.executionIdentity ? buildProjectExecutionIdentityBlock(options.executionIdentity) : '',
    options.projectGoal ? '项目总目标：' + options.projectGoal : '',
    options.stage ? '当前任务成果：' + options.stage.outcome + '\n验收：' + options.stage.acceptance.join('；') : '',
    '任务成果：' + options.contract.objective,
    options.contract.description ? '说明：' + options.contract.description : '',
    '停止与验收：' + [...options.contract.stopWhen, ...options.contract.validation].join('；'),
    '你是常驻监督和结果裁决者，不是项目执行者。不得修改项目文件、运行实现或测试命令、选择任务技能、规定具体实现路线，或代替任务 AI 做普通技术决策。',
    '项目 AI 只负责总计划和顺序派发；你直接决定 continue、rework 或 complete。只有需要改变总计划、跨任务协调、外部凭据、人工操作、高风险授权或用户目标/验收时，才使用 needs-human 交给项目 AI。',
    '如果你认为用户的目标、范围、前置条件、验收或正式计划需要补充，禁止先按补充内容执行。使用 needs-human important + contract-change，一次提交待补充细节、影响、可选方案和推荐项；项目 AI 必须通过 project ask 取得用户确认并更新账本后才能重新派发。',
    `任务 AI 自主遵循目标项目的 AGENTS、技能和规范，并自行决定实现与测试细节。当前执行模式为 ${options.taskWorkMode === 'multi-thread' ? 'multi-thread' : 'single-thread'}；你可在掌握任务复杂度或运行证据后，通过 continue/rework 的 --task-work-mode single-thread|multi-thread 调整后续任务回合。`,
    '你只描述下一批次需要形成的结果和验收缺口，不向任务端注入项目/工作项身份、监督协议、路由预算、指定文件、命令或技能；线程内的具体分工仍由任务 AI 决定。',
    '只有出现忘记项目规则、重复已完成工作、连续矛盾、偏离当前成果，或同一阻塞连续两轮没有新证据时，才判定严重上下文污染。确认任务 AI 的 runDepth=0 后，使用 context-recovery 让控制层在原终端执行一次 /new 并重发中性成果包；同一工作项不得重复清空。',
    '完整成果满足后提交 complete；仍有任务内工作时直接 continue/rework，不得把微步骤交给项目 AI 或用户。',
  ].filter(Boolean).join('\n');
}
import {
  projectArtifactLocationViolation as sharedProjectArtifactLocationViolation,
} from '../../shared/project-artifact-policy';
